name: sync2gitlab

on:
  [push, pull_request]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: keninkujovic/gitlab-sync@2.0.0
      with:
        gitlab_url: ${{secrets.GITLAB_URL}}
        username: ${{secrets.GITLAB_USERNAME}}
        gitlab_pat: ${{secrets.GITLAB_PAT}}
